server:
  port: 9000

spring:
  datasource:
    sampleapp:
      url: jdbc:postgresql://localhost/sampledb
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver
      defaultSchema:
      maxPoolSize: 20
      hibernate:
        ddl-auto: none
        hbm2ddl.method: validate
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

